# -*- coding: utf-8 -*-
"""iris_ml_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sem0cafZnddzN004gc81IYTWrX98juPP
"""

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

from __future__ import print_function
iris = load_iris()

x = iris.data
y = iris.target

print("Feature names:", iris.feature_names)
print("Target names:", iris.target_names)

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.1, random_state=42)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

predictions = model.predict(X_test)
print(predictions)

accuracy = accuracy_score(y_test, predictions)
print("Model accuracy:", accuracy)

my_flower = [[6.5, 3.0, 6.0, 2.2]]

prediction = model.predict(my_flower)
print("Predicted class:", prediction)
print("Flower Type:", iris.target_names[prediction[0]])

